export default {
  'arcane-botcenter.xyz': {
    api_docs: 'https://arcane-botcenter.xyz/documentation',
    api_post: 'https://arcane-botcenter.xyz/api/:id/stats',
    api_field: 'server_count',
    api_shard_id: null,
    api_shard_count: 'shard_count',
    api_shards: null,
    api_get: null,
    api_all: null,
  },
  'botlist.space': {
    api_docs: 'https://docs.botlist.space/',
    api_post: 'https://api.botlist.space/v1/bots/:id',
    api_field: 'server_count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: 'shards',
    api_get: 'https://api.botlist.space/v1/bots/:id',
    api_all: 'https://api.botlist.space/v1/bots',
  },
  'bots.ondiscord.xyz': {
    api_docs: 'https://bots.ondiscord.xyz/info/api',
    api_post: 'https://bots.ondiscord.xyz/bot-api/bots/:id/guilds',
    api_field: 'guildCount',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: null,
    api_all: null,
  },
  'botsfordiscord.com': {
    api_docs: 'https://botsfordiscord.gitbook.io/docs/',
    api_post: 'https://botsfordiscord.com/api/bot/:id',
    api_field: 'server_count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://botsfordiscord.com/api/bot/:id',
    api_all: null,
  },
  'cloud-botlist.xyz': {
    api_docs: 'https://apollos.gitbook.io/cloud-botlist/',
    api_post: 'https://cloud-botlist.xyz/api/bots/:id',
    api_field: 'guilds',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://cloud-botlist.xyz/api/bots/:id',
    api_all: null,
  },
  'cloudlist.xyz': {
    api_docs: 'https://www.cloudlist.xyz/apidocs',
    api_post: 'https://www.cloudlist.xyz/api/stats/:id',
    api_field: 'count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://www.cloudlist.xyz/api/bot/:id',
    api_all: null,
  },
  'dblista.pl': {
    api_docs: 'https://dblista.pl/docs',
    api_post: 'https://dblista.pl/api/v1/stats/:id',
    api_field: 'servers',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://dblista.pl/api/v1/bot/:id',
    api_all: 'https://dblista.pl/api/v1/bots',
  },
  'discord.boats': {
    api_docs: 'https://docs.discord.boats/',
    api_post: 'https://discord.boats/api/bot/:id',
    api_field: 'server_count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://discord.boats/api/bot/:id',
    api_all: null,
  },
  'discord.bots.gg': {
    api_docs: 'https://discord.bots.gg/docs',
    api_post: 'https://discord.bots.gg/api/v1/bots/:id/stats',
    api_field: 'guildCount',
    api_shard_id: 'shardId',
    api_shard_count: 'shardCount',
    api_shards: null,
    api_get: 'https://discord.bots.gg/api/v1/bots/:id',
    api_all:
      'https://discord.bots.gg/api/v1/bots?limit=100&sort=guildcount&order=desc',
  },
  'discordapps.dev': {
    api_docs: 'https://discordapps.dev/en-GB/posts/docs/api-v2/',
    api_post: 'https://api.discordapps.dev/api/v2/bots/:id',
    api_field: 'bot.count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://api.discordapps.dev/api/v2/bots/:id',
    api_all: 'https://api.discordapps.dev/api/v2/bots',
  },
  'discordbot.world': {
    api_docs: 'https://discordbot.world/docs',
    api_post: 'https://discordbot.world/api/bot/:id/stats',
    api_field: 'guild_count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: 'shards',
    api_get: 'https://discordbot.world/api/bot/:id',
    api_all: 'https://discordbot.world/api/bots',
  },
  'discordbotlist.com': {
    api_docs: 'https://discordbotlist.com/api-docs',
    api_post: 'https://discordbotlist.com/api/bots/:id/stats',
    api_field: 'guilds',
    api_shard_id: 'shard_id',
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://discordbotlist.com/api/bots/:id',
    api_all: 'https://discordbotlist.com/api/bots',
  },
  'discordextremelist.xyz': {
    api_docs: 'https://docs.discordextremelist.xyz',
    api_post: 'https://api.discordextremelist.xyz/v1/bot/:id',
    api_field: 'guildCount',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://api.discordextremelist.xyz/v1/bot/:id',
    api_all: null,
  },
  'divinediscordbots.com': {
    api_docs: 'https://divinediscordbots.com/api',
    api_post: 'https://divinediscordbots.com/bot/:id/stats',
    api_field: 'server_count',
    api_shard_id: null,
    api_shard_count: 'shards',
    api_shards: null,
    api_get: 'https://divinediscordbots.com/bot/:id/stats',
    api_all: null,
  },
  'glennbotlist.xyz': {
    api_docs: 'https://docs.glennbotlist.xyz/',
    api_post: 'https://glennbotlist.xyz/api/v2/bot/:id/stats',
    api_field: 'serverCount',
    api_shard_id: null,
    api_shard_count: 'shardCount',
    api_shards: null,
    api_get: null,
    api_all: null,
  },
  'lbots.org': {
    api_docs: 'https://lbots.org/api/docs',
    api_post: 'https://lbots.org/api/v1/bots/:id/stats',
    api_field: 'guild_count',
    api_shard_id: 'shard_id',
    api_shard_count: 'shard_count',
    api_shards: null,
    api_get: null,
    api_all: null,
  },
  'mythicalbots.xyz': {
    api_docs: 'https://docs.mythicalbots.xyz/',
    api_post: 'https://mythicalbots.xyz/api/bot/:id',
    api_field: 'server_count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://mythicalbots.xyz/api/bot/:id/info',
    api_all: null,
  },
  'space-bot-list.org': {
    api_docs: 'https://spacebots.gitbook.io/tutorial-en/api/stats',
    api_post: 'https://space-bot-list.org/api/bots/:id',
    api_field: 'guilds',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://space-bot-list.org/api/bots/:id',
    api_all: null,
  },
  'top.gg': {
    api_docs: 'https://top.gg/api/docs',
    api_post: 'https://top.gg/api/bots/:id/stats',
    api_field: 'server_count',
    api_shard_id: 'shard_id',
    api_shard_count: 'shard_count',
    api_shards: 'shards',
    api_get: 'https://top.gg/api/bots/:id',
    api_all: null,
  },
  'wonderbotlist.com': {
    api_docs: 'https://api.wonderbotlist.com/en/',
    api_post: 'https://api.wonderbotlist.com/v1/bot/:id',
    api_field: 'serveurs',
    api_shard_id: null,
    api_shard_count: 'shards',
    api_shards: null,
    api_get: 'https://api.wonderbotlist.com/v1/bot/:id',
    api_all: null,
  },
  'yabl.xyz': {
    api_docs: 'https://yabl.xyz/api',
    api_post: 'https://yabl.xyz/api/bot/:id/stats',
    api_field: 'guildCount',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://yabl.xyz/api/bot/:id',
    api_all: 'https://yabl.xyz/api/bots/all',
  },
  'discordbotreviews.xyz': {
    api_docs: 'https://discordbotreviews.xyz/api/docs',
    api_post: 'https://discordbotreviews.xyz/api/bot/:id/stats',
    api_field: 'server_count',
    api_shard_id: null,
    api_shard_count: null,
    api_shards: null,
    api_get: 'https://discordbotreviews.xyz/api/bot/:id',
    api_all: null,
  },
} as listDataType;
