name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
    - name: npm install, build, and test
      run: |
        npm ci
        npm run lint
        npm run build
        npm test --if-present
      env:
        CI: true
